project_name: wlim

builds:
  - id: wlim
    main: ./main.go
    env: [CGO_ENABLED=0]
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X wlim/internal/version.Version={{.Tag}}

archives:
  - builds: [wlim]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

brews:
  - name: wlim
    tap:
      owner: wicklim
      name: homebrew-tap
    folder: Formula
    description: Fast npm-like package installer
    homepage: https://github.com/wicklim/wlim
    license: MIT
    install: |
      bin.install "wlim"
    test: |
      system "#{bin}/wlim", "--help"

release:
  prerelease: false
