name: npm-publish

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Set npm version to match tag
        working-directory: npm
        run: |
          # Derive tag from either push (GITHUB_REF_NAME) or release event
          TAG=${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}
          if [ -z "$TAG" ]; then TAG='${{ github.event.release.tag_name }}'; fi
          VERSION=${TAG#v}
          echo "Setting npm version to $VERSION"
          npm version --no-git-tag-version "$VERSION"
      - name: Publish
        working-directory: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
